### ISSUE TITLE
Support stopforumspam

### ISSUE THREAD

**Issue by pitaj** [akhoury/nodebb-plugin-spam-be-gone#61]
https://www.stopforumspam.com

Would be another good service to support.

**Comment by An-dz** [comment]
I checked the APIs on npm and there are only two, one is not very complete and the other is outdated.

So I heavily modified the more complete API to add support for IPv6, require less dependencies, be more lightweight, use POST instead of GET, use HTTPS, and add support for email hash search.

<https://github.com/An-dz/stopforumspam-npm>

**Comment by barisusakli** [comment]
Dupe https://github.com/akhoury/nodebb-plugin-spam-be-gone/issues/40
